# Generated by Django 2.2.4 on 2019-08-21 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='projects.Project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
