# Generated by Django 2.2.4 on 2019-08-21 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('POSTGRES_DATABASE_URL', 'postgres:// DATABASE_URL'), ('HEROKU_APP', 'Heroku app')], max_length=30)),
                ('connection_value', models.CharField(max_length=255)),
                ('project_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='projects.ProjectInstance')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dump_file', models.FileField(blank=True, upload_to='database_dumps')),
                ('initiated_at', models.DateTimeField(editable=False, null=True)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
                ('log', models.TextField()),
                ('return_code', models.PositiveIntegerField(default=None, null=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dumps', to='databases.Database')),
            ],
        ),
    ]
